export const colors = {
  primary: '#00396b',
  onPrimary: '#ffffff',
  primaryContainer: '#005092',
  onPrimaryContainer: '#9ac3ff',
  secondary: '#48626e',
  onSecondary: '#ffffff',
  secondaryContainer: '#cbe7f5',
  onSecondaryContainer: '#4e6874',
  tertiary: '#5f2800',
  onTertiary: '#ffffff',
  tertiaryContainer: '#823a02',
  onTertiaryContainer: '#ffae80',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  surface: '#f8f9ff',
  onSurface: '#191c20',
  surfaceDim: '#d9dae0',
  surfaceBright: '#f8f9ff',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f3f3f9',
  surfaceContainer: '#ededf4',
  surfaceContainerHigh: '#e7e8ee',
  surfaceContainerHighest: '#e1e2e8',
  onSurfaceVariant: '#424750',
  inverseSurface: '#2e3035',
  inverseOnSurface: '#f0f0f7',
  outline: '#727782',
  outlineVariant: '#c2c6d2',
  surfaceTint: '#2160a2',
  inversePrimary: '#a4c9ff',
  background: '#f8f9ff',
  onBackground: '#191c20',
  surfaceVariant: '#e1e2e8',
} as const;

export const typography = {
  'display-lg': {
    fontFamily: 'Inter',
    fontSize: 32,
    fontWeight: '700' as const,
    lineHeight: 40,
    letterSpacing: -0.02,
  },
  'headline-md': {
    fontFamily: 'Inter',
    fontSize: 20,
    fontWeight: '600' as const,
    lineHeight: 28,
  },
  'headline-md-mobile': {
    fontFamily: 'Inter',
    fontSize: 18,
    fontWeight: '600' as const,
    lineHeight: 26,
  },
  'headline-sm': {
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '600' as const,
    lineHeight: 24,
  },
  'body-lg': {
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '400' as const,
    lineHeight: 24,
  },
  'body-md': {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '400' as const,
    lineHeight: 20,
  },
  'label-md': {
    fontFamily: 'Inter',
    fontSize: 12,
    fontWeight: '500' as const,
    lineHeight: 16,
    letterSpacing: 0.05,
  },
} as const;

export const spacing = {
  base: 8,
  containerPadding: 16,
  stackGap: 12,
  inlineGap: 8,
  sectionMargin: 24,
} as const;

export const borderRadius = {
  sm: 2,
  default: 4,
  md: 6,
  lg: 8,
  xl: 12,
  full: 9999,
} as const;
